# Generated by Django 6.0.4 on 2026-05-02 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='Note UUID')),
                ('title', models.CharField(max_length=200, verbose_name='Note title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Note text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Note created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Note updated at')),
                ('is_important', models.BooleanField(blank=True, default=False, verbose_name='Note is important')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
